# Generated by Django 3.2.7 on 2021-09-30 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_text', models.CharField(max_length=200)),
                ('result_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity_founded', models.IntegerField()),
            ],
        ),
    ]
